[http.routers]
  [http.routers.casdoor]
    entrypoints=["https"]
    rule="Host(`casdoor.kamipon.com`)"
    tls=true
    middlewares=["gzip@file"]
    service = "casdoor-service"

[http.services]
  [http.services.casdoor-service.loadBalancer]
    [[http.services.casdoor-service.loadBalancer.servers]]
      url = "http://10.99.1.2:8000/"