[http.routers]
  [http.routers.vscode]
    entrypoints=["https"]
    rule="Host(`vscode.kamipon.com`,`code.kamipon.com`)"
    tls=true
    middlewares=["gzip@file"]
    service = "vscode-service"

[http.services]
  [http.services.vscode-service.loadBalancer]
    [[http.services.vscode-service.loadBalancer.servers]]
      url = "http://10.99.1.2:3000/"