# 提供 Gzip 压缩
[http.middlewares.gzip.compress]

# tricks 实现，提供 HTTP 默认转发 HTTPS
# https://github.com/containous/traefik/issues/4863#issuecomment-491093096
[http.services]
  [http.services.noop.LoadBalancer]
      [[http.services.noop.LoadBalancer.servers]]
        url = "" # or url = "localhost"

[http.routers]
  [http.routers.https-redirect]
    entryPoints = ["http"]
    rule = "HostRegexp(`{any:.*}`)"
    middlewares = ["https-redirect"]
    priority = 9
    service = "noop"
  [http.routers.https2-redirect]
    entryPoints = ["https"]
    tls = false
    rule = "HostRegexp(`{any:.*}`)"
    middlewares = ["https-redirect"]
    priority = 9
    service = "noop"

[http.middlewares.https-redirect.redirectScheme]
  scheme = "https"
  port = 442
  tls = true
  permanent = true