[http.routers]
  [http.routers.dev_nacos]
    entrypoints=["https"]
    rule="Host(`dev.nacos.kamipon.com`)"
    tls=true
    middlewares=["gzip@file"]
    service = "dev_nacos-service"

[http.services]
  [http.services.dev_nacos-service.loadBalancer]
    [[http.services.dev_nacos-service.loadBalancer.servers]]
      url = "http://10.99.1.102:8848/"