[http.routers]
  [http.routers.dev_gateway]
    entrypoints=["https"]
    rule="Host(`dev_gateway.kamipon.com`)"
    tls=true
    middlewares=["gzip@file"]
    service = "dev_gateway-service"

[http.services]
  [http.services.dev_gateway-service.loadBalancer]
    [[http.services.dev_gateway-service.loadBalancer.servers]]
      url = "http://10.99.1.102:8020/"