[http.routers]
  [http.routers.emby]
    entrypoints=["https"]
    rule="Host(`emby.kamipon.com`)"
    tls=true
    middlewares=["gzip@file","error-pages-middleware@docker"]
    service = "emby-service"
  
  [http.routers.emby-http]
    entrypoints=["http"]
    rule="Host(`emby.kamipon.com`)"
    tls=false
    middlewares=["gzip@file","error-pages-middleware@docker"]
    service = "emby-service"

[http.services]
  [http.services.emby-service.loadBalancer]
    [[http.services.emby-service.loadBalancer.servers]]
      url = "http://10.99.1.14:8096/"