[http.routers]
  [http.routers.gitea]
    entrypoints=["https"]
    rule="HostRegexp(`gitea.kamipon.com`) || HostRegexp(`{subdomain:[.*@]?}gitea.kamipon.com`)"
    tls=true
    # middlewares=["error-pages-middleware@docker"]
    service = "gitea-service"

[http.services]
  [http.services.gitea-service.loadBalancer]
    [[http.services.gitea-service.loadBalancer.servers]]
      url = "http://10.99.1.31:3000/"