[http.routers]
  [http.routers.ha]
    entrypoints=["https"]
    rule="Host(`ha.kamipon.com`)"
    tls=true
    # middlewares=["gzip@file"]
    service = "ha-service"

[http.services]
  [http.services.ha-service.loadBalancer]
    [[http.services.ha-service.loadBalancer.servers]]
      url = "http://10.99.1.2:8123/"