[http.routers]
  [http.routers.hindsight]
    entrypoints=["https"]
    rule="Host(`hindsight.kamipon.com`)"
    tls=true
    middlewares=["gzip@file"]
    service = "hindsight-service"

[http.services]
  [http.services.hindsight-service.loadBalancer]
  [[http.services.hindsight-service.loadBalancer.servers]]
      url = "http://10.99.1.34:9999/"
