[http.routers]
  [http.routers.iyuu]
    entrypoints=["https"]
    rule="Host(`iyuu.kamipon.com`)"
    tls=true
    middlewares=["gzip@file","error-pages-middleware@docker"]
    service = "iyuu-service"

[http.services]
  [http.services.iyuu-service.loadBalancer]
    [[http.services.iyuu-service.loadBalancer.servers]]
      url = "http://10.99.1.2:8192/"