[http.routers]
  [http.routers.jackett]
    entrypoints=["https"]
    rule=Host(`jackett.kamipon.com`)
    tls=true
    middlewares=["gzip@file","error-pages-middleware@docker"]
    service = "jackett-service"

[http.services]
  [http.services.jackett-service.loadBalancer]
    [[http.services.jackett-service.loadBalancer.servers]]
      url = "http://10.99.1.2:9117/"