[http.routers]
  [http.routers.jellyseerr]
    entrypoints=["https"]
    rule="Host(`jellyseerr.kamipon.com`)"
    tls=true
    middlewares=["gzip@file","error-pages-middleware@docker"]
    service = "jellyseerr-service"

[http.services]
  [http.services.jellyseerr-service.loadBalancer]
    [[http.services.jellyseerr-service.loadBalancer.servers]]
      url = "http://10.99.1.2:5055/"