[http.routers]
  [http.routers.k-gateway]
    entrypoints=["https"]
    rule="Host(`k-gateway.kamipon.com`)"
    tls=true
    middlewares=["gzip@file"]
    service = "k-gateway-service"

[http.services]
  [http.services.k-gateway-service.loadBalancer]
    [[http.services.k-gateway-service.loadBalancer.servers]]
      url = "http://10.99.1.102:8020/"