[http.routers]
  [http.routers.k_kibana]
    entrypoints=["https"]
    rule="Host(`k_kibana.kamipon.com`)"
    tls=true
    middlewares=["gzip@file"]
    service = "k_kibana-service"

[http.services]
  [http.services.k_kibana-service.loadBalancer]
    [[http.services.k_kibana-service.loadBalancer.servers]]
      url = "http://10.99.1.102:5601/"