[http.routers]
  [http.routers.k-kibana]
    entrypoints=["https"]
    rule="Host(`k-kibana.kamipon.com`)"
    tls=true
    middlewares=["gzip@file"]
    service = "k-kibana-service"

[http.services]
  [http.services.k-kibana-service.loadBalancer]
    [[http.services.k-kibana-service.loadBalancer.servers]]
      url = "http://10.99.1.102:5601/"