[http.routers]
  [http.routers.k-monitor]
    entrypoints=["https"]
    rule="Host(`k-monitor.kamipon.com`)"
    tls=true
    middlewares=["gzip@file"]
    service = "k-monitor-service"

[http.services]
  [http.services.k-monitor-service.loadBalancer]
    [[http.services.k-monitor-service.loadBalancer.servers]]
      url = "http://10.99.1.102:11100/"