[http.routers]
  [http.routers.k-xxljob]
    entrypoints=["https"]
    rule="Host(`k-xxljob.kamipon.com`)"
    tls=true
    middlewares=["gzip@file"]
    service = "k-xxljob-service"

[http.services]
  [http.services.k-xxljob-service.loadBalancer]
    [[http.services.k-xxljob-service.loadBalancer.servers]]
      url = "http://10.99.1.102:11101/"