[http.routers]
  [http.routers.kavita]
    entrypoints=["https"]
    rule=Host(`kavita.kamipon.com`)
    tls=true
    middlewares=["gzip@file"]
    service = "kavita-service"

[http.services]
  [http.services.kavita-service.loadBalancer]
    [[http.services.kavita-service.loadBalancer.servers]]
      url = "http://10.99.1.2:5020/"