[http.routers]
  [http.routers.nexus]
    entrypoints=["https"]
    rule="Host(`nexus.kamipon.com`)"
    tls=true
    middlewares=["gzip@file"]
    service = "nexus-service"

[http.services]
  [http.services.nexus-service.loadBalancer]
    [[http.services.nexus-service.loadBalancer.servers]]
      url = "http://10.99.1.17:8081/"