[http.routers]
  [http.routers.nodered]
    entrypoints=["https"]
    rule="Host(`nodered.kamipon.com`)"
    tls=true
    # middlewares=["gzip@file"]
    service = "nodered-service"

[http.services]
  [http.services.nodered-service.loadBalancer]
    passHostHeader = true
    [[http.services.nodered-service.loadBalancer.servers]]
      url = "http://10.99.1.2:1880/"