[http.routers]
  [http.routers.photo-tool]
    entrypoints=["https"]
    rule="Host(`photo-tool.kamipon.com`)"
    tls=true
    middlewares=["gzip@file"]
    service = "photo-tool-service"

[http.services]
  [http.services.photo-tool-service.loadBalancer]
    [[http.services.photo-tool-service.loadBalancer.servers]]
      url = "http://10.99.1.2:8001/"