[http.routers]
  [http.routers.plex]
    entrypoints=["https"]
    rule="Host(`plex.kamipon.com`)"
    tls=true
    middlewares=["gzip@file","error-pages-middleware@docker"]
    service = "plex-service"

[http.services]
  [http.services.plex-service.loadBalancer]
    [[http.services.plex-service.loadBalancer.servers]]
      url = "http://10.99.1.2:32400/"