[http.routers]
  [http.routers.prowlarr]
    entrypoints=["https"]
    rule="Host(`prowlarr.kamipon.com`)"
    tls=true
    middlewares=["gzip@file","error-pages-middleware@docker"]
    service = "prowlarr-service"

[http.services]
  [http.services.prowlarr-service.loadBalancer]
    [[http.services.prowlarr-service.loadBalancer.servers]]
      url = "http://10.99.1.2:9696/"