[http.routers]
  [http.routers.pthelper]
    entrypoints=["https"]
    rule=Host(`pthelper.kamipon.com`)
    tls=true
    middlewares=["gzip@file","error-pages-middleware@docker"]
    service = "pthelper-service"

[http.services]
  [http.services.pthelper-service.loadBalancer]
    [[http.services.pthelper-service.loadBalancer.servers]]
      url = "http://10.99.1.2:8192/"