[http.routers]
  [http.routers.qbittorrent]
    entrypoints=["https"]
    rule="Host(`qbittorrent.kamipon.com`,`qb.kamipon.com`,)"
    tls=true
    middlewares=["gzip@file","error-pages-middleware@docker"]
    service = "qbittorrent-service"

[http.services]
  [http.services.qbittorrent-service.loadBalancer]
    [[http.services.qbittorrent-service.loadBalancer.servers]]
      url = "http://10.99.1.13:8080/"