[http.routers]
  [http.routers.registry]
    entrypoints=["https"]
    rule=Host(`registry.kamipon.com`)
    tls=true
    middlewares=["gzip@file"]
    service = "registry-service"

[http.services]
  [http.services.registry-service.loadBalancer]
    [[http.services.registry-service.loadBalancer.servers]]
      url = "http://10.99.1.2:5000"