[http.routers]
  [http.routers.sonarr]
    entrypoints=["https"]
    rule="Host(`sonarr.kamipon.com`)"
    tls=true
    middlewares=["gzip@file","error-pages-middleware@docker"]
    service = "sonarr-service"

[http.services]
  [http.services.sonarr-service.loadBalancer]
    [[http.services.sonarr-service.loadBalancer.servers]]
      url = "http://10.99.1.2:8989/"