[http.routers]
  [http.routers.subconverter]
    entrypoints=["https"]
    rule="Host(`subconverter.kamipon.com`)"
    tls=true
    middlewares=["error-pages-middleware@docker"]
    service = "subconverter-service"

[http.services]
  [http.services.subconverter-service.loadBalancer]
    [[http.services.subconverter-service.loadBalancer.servers]]
      url = "http://10.99.1.102:25500/"