[http.routers]
  [http.routers.transmission]
    entrypoints=["https"]
    rule="Host(`transmission.kamipon.com`,`tr.kamipon.com`,)"
    tls=true
    middlewares=["gzip@file"]
    service = "transmission-service"

[http.services]
  [http.services.transmission-service.loadBalancer]
    [[http.services.transmission-service.loadBalancer.servers]]
      url = "http://10.99.1.17:9091/"