[http.routers]
  [http.routers.unraid]
    entrypoints="https"
    rule="Host(`unraid.kamipon.com`)"
    tls = true
    # middlewares=["error-pages-middleware@docker"]
    middlewares=["gzip@file"]
    service = "unraid-service"

[http.services]
  [http.services.unraid-service.loadBalancer]
    [[http.services.unraid-service.loadBalancer.servers]]
      url = "http://10.99.1.2/"
